### ISSUE TITLE
Several compile errors on MongoDragons2.Database\Concreate\MongoDatabase.cs

### ISSUE THREAD

**Issue by TLKG** [primaryobjects/mongodragons2#1]
I downloaded the latest build (2015), added a few NuGet packages into MongoDragons2.Database project, namely MongoDB.Driver (**v2.4.2**) and its dependencies to iron out "not found" issues for "using".
Compiled and got some errors shown in the screenshot. 
IDE = VS 2015 Community, 
Win10, 64-bit.
![compile err](https://cloud.githubusercontent.com/assets/22269729/22860107/443a09d8-f0a8-11e6-82ef-951f397a6479.JPG)

**Comment by primaryobjects** [comment]
Thanks you! I just [updated](https://github.com/primaryobjects/mongodragons2/commit/8221fd2c38bfce931cf126cc04952be412884f33) the Mongo driver in the project to the latest version. This fixes the build problems.

I've also updated angularjs and jquery to their latest versions.

**Comment by TLKG** [comment]
Awesome, looks great!
For project .Database, Concrete\MongoDatabase.cs

```
namespace MongoDragons2.Database.Concrete
{
    public class MongoDatabase<T> : IDatabase<T> where T : class, new()
```

My interpretation is:
Class "MongoDatabase" is a type (T).
This class inherits/implements interface "IDatabase".
The interface is a type (T), can be instantiated as a "class" by a parameterless constructor, new().

But why we define another constructor taking parameter? Would it violates the definition of aforementioned interface ?
`public MongoDatabase(string collectionName) `
